# Generated by Django 2.1 on 2019-01-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestcondition',
            name='close_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtestcondition',
            name='open_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
