# Generated by Django 2.1.7 on 2019-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0002_auto_20190103_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestcondition',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtestcondition',
            name='open_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='code',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='security',
            name='exchange',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
