# Generated by Django 2.1.7 on 2019-03-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0003_auto_20190309_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtestcondition',
            old_name='daily_return',
            new_name='return_rate',
        ),
    ]
