# Generated by Django 2.1.7 on 2019-03-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0004_auto_20190314_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
