# Generated by Django 2.1.7 on 2019-04-05 15:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0005_security_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('symbol', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('tickers', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.AddField(
            model_name='security',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='index',
            field=models.ManyToManyField(to='predictapp.Index'),
        ),
    ]
