# Generated by Django 2.1.7 on 2019-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0006_auto_20190405_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
