# Generated by Django 2.1.7 on 2019-04-11 21:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0007_index_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='tickers',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
